# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='ano',
            field=models.IntegerField(default=2017, verbose_name='ano'),
        ),
    ]
