# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-28 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0002_auto_20170420_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Gestores',
                'verbose_name': 'Gestor',
            },
        ),
        migrations.AlterField(
            model_name='plano',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='accounts.Dono', verbose_name='dono'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Plano', verbose_name='gestores'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário no sistema'),
        ),
    ]
