# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170428_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestores_set', to='plan.Plano', verbose_name='gestores'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário no sistema'),
        ),
    ]
