# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170501_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='created_at',
        ),
    ]
