# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('cod_ibge', models.IntegerField(verbose_name='código do IBGE')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('alt', models.FloatField(help_text='metros acima do nível do mar', verbose_name='altitude')),
            ],
            options={
                'verbose_name': 'município',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('sigla', models.CharField(blank=True, max_length=4, verbose_name='sigla')),
                ('regiao', models.CharField(max_length=50, verbose_name='região')),
                ('avatar', models.CharField(blank=True, max_length=500, verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'Unidade da Federação (UF)',
                'verbose_name_plural': "Unidades da Federação (UF's)",
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='UF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.UF', verbose_name='Unidade da Federação'),
        ),
    ]
