from .universalizacao import *
from .tecnologia import *
from .adequacao import *
from .sustentabilidade import *
from .indicadores import *
from .planomunicipal import *
from .servicosprestados import *
from .controlesocial import *
from .fiscalizacao import *
from .intersetorialidade import *
from .revisao import *
